services:
  bot:
    build: .
    restart: always
    env_file: .env
    volumes:
      - ./assets:/app/assets
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
